---
- hosts: ubuntu
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
  
  - name: Change file ownership to www-data
    ansible.builtin.file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Rename index.nginx-debian.html to index.html
    ansible.builtin.shell: mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

  - name: Create nginx.conf file
    ansible.builtin.template:
      src: ubuntu/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

    notify:
      - Restart nginx

  handlers: 
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true


- hosts: centos
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Install epel repository
    ansible.builtin.yum:
      name: epel-release
      state: present

  - name: Install nginx
    ansible.builtin.yum:
      name: nginx

  - name: Create nginx.conf file
    ansible.builtin.template:
      src: centos/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

    notify:
      - Start nginx

  handlers:
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: true
