---
- hosts: ubuntu
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Update repository index
    apt:
      update_cache: yes
    tags: 
    - update_cache

  - name: Install nginx
    apt:
      name: nginx
    tags:
    - install_nginx
  
  - name: Change file ownership to www-data
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Rename index.nginx-debian.html to index.html
    shell: mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

  - name: Create nginx.conf file
    template:
      src: ubuntu/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

    notify:
      - Restart nginx

  handlers: 
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true


- hosts: centos
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Install epel repository
    yum:
      name: epel-release
      state: present
    tags:
    - install_epel

  - name: Install nginx
    yum:
      name: nginx
    tags:
    - install_nginx

  - name: Create nginx.conf file
    template:
      src: centos/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

    notify:
      - Start nginx

  handlers:
  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: true
